language: node_js
node_js:
  - "0.12"
before_script:
 - chmod +x ./script/cibuild # or do this locally and commit
script: ./script/cibuild
after_success:
  - surge --project ./_site --domain www.boringgeek.com
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
