name: BoringGeek
description: Who says geeks are boring?
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.boringgeek.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://www.boringgeek.com'
author:         'Curtis Rissi'
author-bio:     'Solution Architect and Full Stack Engineer by day and mad scientist by night. I specialize in making the impossible possible through code and technology. I also make some crazy good Korean BBQ. You know you want to try it.'
author-pic:     'http://assets.boringgeek.com/curtis_rissi_speak_no_evil.jpg'
