name: Boring Geek
description: Who says geeks are boring?
meta_description: "Who says geeks are boring? The personal blog of Solutions Architect and Full Stack Engineer, Curtis Rissi."
site_cover: http://assets.boringgeek.com/imacSceneryReduced.jpg
baseurl: /
domain_name: 'http://www.boringgeek.com'
google_analytics: 'UA-12222555-1'
logo: false

# Plugins
gems: ['jekyll-paginate']
paginate: 15

# Conversion
markdown: kramdown
highlighter: rouge

# Details for the RSS feed generator
url:            'http://www.boringgeek.com'
author:         'Curtis Rissi'
author-bio:     'Solutions Architect and Full Stack Engineer by day and mad scientist by night. I specialize in making the impossible possible through code and technology. I also make some crazy good Korean BBQ. You know you want to try it. <br /><br/><strong>Disclaimer:</strong> I work for AWS, but unless otherwise stated, the words and thoughts expressed in this blog are my own.'
author-pic:     'http://assets.boringgeek.com/curtis_rissi_speak_no_evil.jpg'
author-location: 'Redlands, CA'
author-link:    'http://www.curtisrissi.com'

# Tagging Config
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Kramdown Config
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
